# Generated by Django 4.2 on 2024-07-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('contenido', models.TextField()),
                ('fecha_publica', models.DateTimeField()),
            ],
            options={
                'db_table': 'noticia',
                'managed': False,
            },
        ),
    ]
