# Generated by Django 4.2 on 2024-07-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudios', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
            ],
        ),
    ]
