# Generated by Django 4.2 on 2024-07-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educacion',
            new_name='Education',
        ),
    ]
